"""
Video generation with Google Veo, through the Gemini API -- and the entry
point for every video model: Gemini Omni Flash requests are handed to
`omni.py`, which works differently (see there), but share the same job/poll
flow, gallery and sidecars.

Replaces Sora: OpenAI shut the Sora API down on 2026-09-24. Veo renders take
a minute or more, so this works like the old flow -- start a long-running
operation, return its name as the job id, and let the page poll until it is
done; the finished MP4 is downloaded into the same gallery as the images.

Plain REST over httpx rather than the google-genai SDK: it is three calls
(start, poll, download), and the SDK would be a large dependency for that.

A render can start from one of the generated images -- typically a finished
ULTEx ad -- so the clip opens on the real logo and layout instead of Veo
inventing a brand it cannot draw.

**Extension.** One Veo request is at most 8 seconds. Veo 3.1 can *extend* a
video it generated by 7 seconds at a time, up to 20 times (~148s), as one
continuous shot -- 720p only. Every finished Veo video gets a sidecar
`<file>.json` with what an extension needs (model, aspect, resolution,
length, Google's file uri), so any gallery video made here can be extended
later, and each extension is saved as a new file that can be extended again.
"""

from __future__ import annotations

import base64
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import httpx

from .config import get_settings
from .creative import OUTPUT_DIR, CreativeNotConfigured, _slug, asset_path, load_persona

API = "https://generativelanguage.googleapis.com/v1beta"

OMNI_MODELS = ["gemini-omni-1.1-flash", "gemini-omni-flash-preview"]
VIDEO_MODELS = [
    "veo-3.1-generate-preview",
    "veo-3.1-fast-generate-preview",
    "veo-3.1-lite-generate-preview",
    *OMNI_MODELS,
]
DEFAULT_VIDEO_MODEL = "veo-3.1-generate-preview"
VIDEO_ASPECTS = {"portrait": "9:16", "landscape": "16:9"}
VIDEO_SECONDS = ("4", "6", "8")
VIDEO_RESOLUTIONS = ("720p", "1080p", "4k")
# 4k is Veo 3.1 and 3.1 fast only; lite stops at 1080p.
RESOLUTIONS_BY_MODEL = {
    "veo-3.1-generate-preview": ["720p", "1080p", "4k"],
    "veo-3.1-fast-generate-preview": ["720p", "1080p", "4k"],
    "veo-3.1-lite-generate-preview": ["720p", "1080p"],
    # Omni renders 360p/720p; 1080p and 4k are upscaled.
    "gemini-omni-1.1-flash": ["360p", "720p", "1080p", "4k"],
    "gemini-omni-flash-preview": ["360p", "720p", "1080p", "4k"],
}

# Price per second of generated video (audio included), from
# ai.google.dev/gemini-api/docs/pricing as of 2026-10-01. Google bills only
# videos that are actually generated. Update here when the page changes.
PRICING_SOURCE = "ai.google.dev/gemini-api/docs/pricing (checked 2026-10-01)"
_VEO_LIMITS = {"provider": "veo", "seconds": [4, 6, 8], "extendSeconds": 7,
               "maxTotalSeconds": 148, "extendResolution": "720p"}
# Omni bills tokens: 5,792 output tokens per second of 720p video at $17.50
# per 1M = ~$0.10/s. Google publishes no per-second figure for the other
# resolutions, so the page estimates them at the 720p rate.
_OMNI_LIMITS = {"provider": "omni", "seconds": None, "lengthNote": "~5-10s, timed by the prompt",
                "extendSeconds": 10, "maxTotalSeconds": 40, "extendResolution": None,
                "pricePerSecond": {"720p": 0.1014}, "priceNote": "token-billed; 720p rate"}
VIDEO_MODEL_INFO = {
    "veo-3.1-generate-preview": {
        **_VEO_LIMITS, "label": "Veo 3.1", "tier": "best quality",
        "pricePerSecond": {"720p": 0.40, "1080p": 0.40, "4k": 0.60}, "canExtend": True,
    },
    "veo-3.1-fast-generate-preview": {
        **_VEO_LIMITS, "label": "Veo 3.1 fast", "tier": "good quality, cheaper",
        "pricePerSecond": {"720p": 0.10, "1080p": 0.12, "4k": 0.30}, "canExtend": True,
    },
    "veo-3.1-lite-generate-preview": {
        **_VEO_LIMITS, "label": "Veo 3.1 lite", "tier": "cheapest, for drafts",
        "pricePerSecond": {"720p": 0.05, "1080p": 0.08}, "canExtend": False,
    },
    "gemini-omni-1.1-flash": {
        **_OMNI_LIMITS, "label": "Gemini Omni 1.1 Flash", "tier": "fast, editable", "canExtend": True,
    },
    "gemini-omni-flash-preview": {
        **_OMNI_LIMITS, "label": "Gemini Omni Flash (preview)", "tier": "earlier preview", "canExtend": True,
    },
}

# Extension limits, from the Gemini API docs.
EXTEND_SECONDS = 7
MAX_EXTENDABLE_SECONDS = 141
MAX_EXTENSIONS = 20
EXTEND_MODELS = ["veo-3.1-generate-preview", "veo-3.1-fast-generate-preview"]
# Inline uploads above this go by Google's file uri instead, to stay well
# inside the request size limit.
INLINE_LIMIT = 14 * 1024 * 1024

# Operation names look like models/veo-3.1-generate-preview/operations/abc123.
# They come back in a URL, so only that exact shape is accepted.
_OPERATION = re.compile(r"^models/veo[\w.\-]+/operations/[\w\-]+$")

# What each running job was started with, written to the sidecar when it
# finishes. In memory only: after a restart a finished job still downloads,
# its sidecar just knows less (and the length is unknown).
_JOBS: dict[str, dict[str, Any]] = {}

NEGATIVE = (
    "chaotic or damaged cargo, dark gloomy scenes, stock-photo handshakes, people "
    "pointing at charts, neon or cyberpunk glow, distorted or invented logos, "
    "misspelled text, watermarks"
)


def video_kit() -> dict[str, Any]:
    """Video options for the studio page, merged into the brand kit."""
    settings = get_settings()
    return {
        "videoProvider": "veo" if settings.gemini_api_key else None,
        "videoModels": VIDEO_MODELS,
        "defaultVideoModel": settings.gemini_video_model or DEFAULT_VIDEO_MODEL,
        "videoSizes": list(VIDEO_ASPECTS),
        "videoSeconds": list(VIDEO_SECONDS),
        "videoResolutions": list(VIDEO_RESOLUTIONS),
        "videoResolutionsByModel": RESOLUTIONS_BY_MODEL,
        "extendModels": EXTEND_MODELS,
        "extendSeconds": EXTEND_SECONDS,
        "maxExtendableSeconds": MAX_EXTENDABLE_SECONDS,
        "maxExtensions": MAX_EXTENSIONS,
        "videoModelInfo": VIDEO_MODEL_INFO,
        "pricingSource": PRICING_SOURCE,
    }


def _key() -> str:
    key = get_settings().gemini_api_key
    if not key:
        raise CreativeNotConfigured(
            "Video needs GEMINI_API_KEY in .env.local (Google AI Studio key with billing)."
        )
    return key


def _persona_for_video(limit: int = 2500) -> str:
    """The parts of the persona that matter on video.

    The full persona is mostly poster layout rules; sending all of it would
    push a video model towards static typography. Who we are, tone and colours
    carry over.
    """
    persona = load_persona()
    if not persona:
        return ""
    wanted = ("who we are", "audience", "tone", "colours", "colors")
    sections = re.split(r"(?m)^## ", persona)
    kept = [s for s in sections if s.strip().lower().startswith(wanted)]
    return ("## " + "\n## ".join(s.strip() for s in kept))[:limit] if kept else ""


def video_prompt(prompt: str, *, use_persona: bool, start_image: bool) -> str:
    parts = []
    # A scene from the idea generator already carries the brand, the look and
    # the continuity bible; adding the persona on top only pushes the prompt
    # towards Veo's length limit and dilutes the shot description.
    detailed = len(prompt) > 700
    brand = _persona_for_video() if use_persona and not detailed else ""
    if brand:
        parts.append(f"Brand context:\n{brand}")
    parts.append(
        "A short, premium vertical advertising clip for Instagram and Facebook Reels. "
        "Clean, controlled, orderly look; navy and white with brand blue and a "
        "sparing yellow accent; soft natural or studio light. Real Moroccan places "
        "where relevant (Casablanca port, Tanger Med, warehouses near Casablanca). "
        "The first second must stop the scroll. Sound: natural ambient sound; any "
        "voice-over or dialogue is in French with a Moroccan business register."
    )
    if start_image:
        parts.append(
            "The video starts from the supplied image, an ULTEx ad. Keep its logo, "
            "colours and any text exactly as they are - never redraw, change or add "
            "letters - and bring the scene to life around them with subtle, "
            "deliberate motion and a slow camera move."
        )
    else:
        parts.append("Do not draw any logo or brand name. No on-screen text.")
    parts.append(f"The video to make:\n{prompt.strip()}")
    return "\n\n".join(parts)


def extension_prompt(prompt: str) -> str:
    """Short on purpose: the video itself carries the look, the brand and the
    scene -- the prompt only has to say what happens next."""
    return (
        "Continue this video seamlessly from its last frame as one continuous shot: "
        "same scene, people, lighting, colours, camera style and sound. Keep any logo "
        "or text already on screen exactly as it is; do not add new text. Any "
        "voice-over stays in French.\n\n"
        f"What happens next:\n{prompt.strip()}"
    )


def _start_image(name: str) -> dict[str, str] | None:
    path = asset_path(name) if name else None
    if not path or path.suffix.lower() not in {".png", ".jpg", ".jpeg", ".webp"}:
        return None
    mime = {".png": "image/png", ".webp": "image/webp"}.get(path.suffix.lower(), "image/jpeg")
    return {"mime": mime, "data": base64.b64encode(path.read_bytes()).decode()}


def _google_error(response: httpx.Response) -> str:
    try:
        error = response.json().get("error", {})
        return error.get("message") or response.text[:300]
    except ValueError:
        return response.text[:300]


class VeoError(RuntimeError):
    def __init__(self, status: int, message: str):
        super().__init__(message)
        self.status = status
        self.message = message


# ------------------------------------------------------------------- sidecars

def _sidecar(video: Path) -> Path:
    return video.with_name(video.name + ".json")


def video_meta(name: str) -> dict[str, Any] | None:
    """The Veo details saved next to a gallery video, or None if it has none."""
    path = asset_path(name) if name else None
    if not path or path.suffix.lower() != ".mp4":
        return None
    side = _sidecar(path)
    if not side.exists():
        return None
    try:
        return json.loads(side.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def mp4_seconds(data: bytes) -> float | None:
    """Duration from the MP4's mvhd box -- the real length, whatever the model
    decided, without ffmpeg."""
    i = data.find(b"mvhd")
    if i < 0:
        return None
    i += 4
    try:
        if data[i] == 1:
            scale = int.from_bytes(data[i + 20:i + 24], "big")
            duration = int.from_bytes(data[i + 24:i + 32], "big")
        else:
            scale = int.from_bytes(data[i + 12:i + 16], "big")
            duration = int.from_bytes(data[i + 16:i + 20], "big")
    except IndexError:
        return None
    return round(duration / scale, 1) if scale else None


def save_video(raw: bytes, meta: dict[str, Any], *, tail: str) -> tuple[str, float | None]:
    """Write a finished video and its sidecar into the gallery."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    label = meta.get("rootPrompt") or meta.get("prompt") or "video"
    suffix = f"-ext{meta['extensions']}" if meta.get("extensions") else ""
    name = f"{stamp}-{_slug(label)}{suffix}-{tail}.mp4"
    path = OUTPUT_DIR / name
    path.write_bytes(raw)
    seconds = mp4_seconds(raw) or meta.get("seconds")
    _sidecar(path).write_text(json.dumps({
        **meta, "seconds": seconds, "createdAt": datetime.now(timezone.utc).isoformat(),
    }, ensure_ascii=False, indent=1), encoding="utf-8")
    return name, seconds


# ------------------------------------------------------------------- requests

async def _submit(model: str, instance: dict[str, Any], parameters: dict[str, Any]) -> str:
    async with httpx.AsyncClient(timeout=120.0) as http:
        response = await http.post(
            f"{API}/models/{model}:predictLongRunning",
            headers={"x-goog-api-key": _key()},
            json={"instances": [instance], "parameters": parameters},
        )
    if response.status_code != 200:
        raise VeoError(response.status_code, _google_error(response))
    return response.json().get("name", "")


async def start_video(
    prompt: str,
    *,
    size: str = "portrait",
    seconds: str = "8",
    resolution: str = "720p",
    model: str | None = None,
    start_image: str | None = None,
    use_persona: bool = True,
) -> dict[str, Any]:
    """Start a render; returns at once with the job to poll."""
    _key()
    model = model if model in VIDEO_MODELS else (get_settings().gemini_video_model or DEFAULT_VIDEO_MODEL)
    if model in OMNI_MODELS:
        from . import omni
        return await omni.start(
            prompt, model=model, aspect=VIDEO_ASPECTS.get(size, VIDEO_ASPECTS["portrait"]),
            resolution=resolution, start_image=start_image, use_persona=use_persona,
        )
    seconds = seconds if seconds in VIDEO_SECONDS else "8"
    allowed = RESOLUTIONS_BY_MODEL.get(model, ["720p", "1080p"])
    resolution = resolution if resolution in allowed else "720p"
    if resolution != "720p":
        # Veo renders 1080p and 4k only at 8 seconds.
        seconds = "8"
    aspect = VIDEO_ASPECTS.get(size, VIDEO_ASPECTS["portrait"])
    image = _start_image(start_image) if start_image else None

    instance: dict[str, Any] = {
        "prompt": video_prompt(prompt, use_persona=use_persona, start_image=bool(image)),
    }
    parameters = {
        "aspectRatio": aspect,
        "durationSeconds": int(seconds),
        "resolution": resolution,
        "negativePrompt": NEGATIVE,
    }

    if image:
        # The Gemini API documents inlineData for the start frame; Vertex uses
        # bytesBase64Encoded. Fall back to the second if the first is rejected.
        try:
            name = await _submit(model, {**instance, "image": {
                "inlineData": {"mimeType": image["mime"], "data": image["data"]}}}, parameters)
        except VeoError as error:
            if error.status != 400 or "inlineData" not in error.message:
                raise
            name = await _submit(model, {**instance, "image": {
                "bytesBase64Encoded": image["data"], "mimeType": image["mime"]}}, parameters)
    else:
        name = await _submit(model, instance, parameters)

    _JOBS[name] = {
        "provider": "veo",
        "prompt": prompt, "model": model, "aspect": aspect, "resolution": resolution,
        "seconds": int(seconds), "startImage": start_image if image else None,
        "parent": None, "extensions": 0, "rootPrompt": prompt,
    }
    return {
        "id": name, "status": "queued", "progress": 0, "kind": "video", "prompt": prompt,
        "seconds": seconds, "aspect": aspect, "resolution": resolution, "model": model,
        "startImage": start_image if image else None,
    }


async def extend_video(
    source: str,
    prompt: str,
    *,
    model: str | None = None,
) -> dict[str, Any]:
    """Continue a gallery Veo video by 7 seconds, as one continuous shot.

    The result is the whole video (original + extension) in one new file; the
    source file is kept, so a bad continuation costs nothing but the render.
    """
    _key()
    path = asset_path(source) if source else None
    meta = video_meta(source)
    if not path or meta is None:
        raise VeoError(400, "Only videos generated here with Veo or Omni Flash can be extended.")
    if meta.get("provider") == "omni":
        # Omni continues its own interaction; a Veo model cannot extend it.
        from . import omni
        return await omni.extend(source, prompt, meta)
    if meta.get("resolution") not in (None, "720p"):
        raise VeoError(400, f"Veo can only extend 720p videos; this one is {meta['resolution']}.")
    length = meta.get("seconds")
    if length and length > MAX_EXTENDABLE_SECONDS:
        raise VeoError(400, f"This video is {length}s; Veo extends videos up to {MAX_EXTENDABLE_SECONDS}s.")
    if (meta.get("extensions") or 0) >= MAX_EXTENSIONS:
        raise VeoError(400, f"Veo allows at most {MAX_EXTENSIONS} extensions.")

    if model not in EXTEND_MODELS:
        model = meta.get("model") if meta.get("model") in EXTEND_MODELS else "veo-3.1-fast-generate-preview"
    parameters: dict[str, Any] = {"resolution": "720p", "durationSeconds": 8, "negativePrompt": NEGATIVE}
    if meta.get("aspect"):
        parameters["aspectRatio"] = meta["aspect"]

    instance = {"prompt": extension_prompt(prompt)}
    data = path.read_bytes()
    inline = {"video": {"inlineData": {"mimeType": "video/mp4", "data": base64.b64encode(data).decode()}}}
    by_uri = {"video": {"uri": meta["uri"]}} if meta.get("uri") else None

    # The docs send the video inline; a long video is safer by the uri Google
    # gave us (kept for 2 days, and reset each time it is extended). Each
    # form is the fallback for the other.
    attempts = [inline, by_uri] if len(data) <= INLINE_LIMIT or not by_uri else [by_uri, inline]
    last: VeoError | None = None
    name = ""
    for video_field in attempts:
        if video_field is None:
            continue
        try:
            name = await _submit(model, {**instance, **video_field}, parameters)
            break
        except VeoError as error:
            last = error
            if error.status != 400:
                raise
    if not name:
        raise last or VeoError(400, "Veo rejected the extension request.")

    _JOBS[name] = {
        "provider": "veo",
        "prompt": prompt, "model": model, "aspect": meta.get("aspect"), "resolution": "720p",
        "seconds": (length + EXTEND_SECONDS) if length else None,
        "startImage": meta.get("startImage"), "parent": source,
        "extensions": (meta.get("extensions") or 0) + 1,
        "rootPrompt": meta.get("rootPrompt") or meta.get("prompt") or prompt,
    }
    return {
        "id": name, "status": "queued", "progress": 0, "kind": "video", "prompt": prompt,
        "model": model, "source": source,
        "seconds": _JOBS[name]["seconds"], "extensions": _JOBS[name]["extensions"],
    }


async def video_status(operation: str) -> dict[str, Any]:
    """Poll a render; downloads the MP4 into the gallery once it is done."""
    if (operation or "").startswith("omni-"):
        from . import omni
        return await omni.status(operation)
    if not _OPERATION.match(operation or ""):
        raise VeoError(400, "Not a Veo job id")
    key = _key()
    tail = operation.rsplit("/", 1)[-1][-10:]
    payload: dict[str, Any] = {"id": operation, "status": "in_progress", "progress": 0}

    # Already downloaded on an earlier poll: do not fetch it again.
    existing = sorted(OUTPUT_DIR.glob(f"*{tail}.mp4"))
    if existing:
        name = existing[0].name
        payload.update({"status": "completed", "progress": 100, "file": name,
                        "url": f"/api/creative/asset/{name}"})
        return payload

    async with httpx.AsyncClient(timeout=180.0, follow_redirects=True) as http:
        r = await http.get(f"{API}/{operation}", headers={"x-goog-api-key": key})
        if r.status_code != 200:
            raise VeoError(r.status_code, _google_error(r))
        op = r.json()
        if not op.get("done"):
            return payload

        if op.get("error"):
            payload.update({"status": "failed", "error": op["error"].get("message", "Render failed")})
            return payload

        result = (op.get("response") or {}).get("generateVideoResponse") or {}
        samples = result.get("generatedSamples") or []
        uri = samples[0].get("video", {}).get("uri") if samples else None
        if not uri:
            reasons = result.get("raiMediaFilteredReasons") or []
            payload.update({
                "status": "failed",
                "error": "Veo's safety filter blocked this video"
                         + (f": {reasons[0]}" if reasons else "") + ". Rephrase the prompt and try again.",
            })
            return payload

        video = await http.get(uri, headers={"x-goog-api-key": key})
        if video.status_code != 200:
            raise VeoError(video.status_code, "Could not download the finished video")

    job = _JOBS.pop(operation, {})
    meta = {
        "provider": "veo", **job, "operation": operation, "uri": uri,
        "model": job.get("model") or operation.split("/")[1],
    }
    name, seconds = save_video(video.content, meta, tail=tail)
    payload.update({"status": "completed", "progress": 100, "file": name,
                    "url": f"/api/creative/asset/{name}", "bytes": len(video.content),
                    "seconds": seconds})
    return payload
