/**
 * French interface text, keyed by the English it replaces (see i18n.jsx).
 * A missing entry simply shows the English, so adding a string to the UI
 * never breaks the French view -- add its translation here.
 */
const FR = {
  "+ Add scene": "+ Ajouter une scène",
  ", plus placement, device and audience breakdowns and the audit. Ask me what to change.": ", ainsi que les répartitions par placement, appareil et audience, et l'audit. Demandez-moi quoi changer.",
  "720p only,": "720p uniquement,",
  "8s only": "8 s uniquement",
  "Account": "Compte",
  "account": "compte",
  "Account health": "Santé du compte",
  "Account median": "Médiane du compte",
  "Accounts": "Comptes",
  "across active campaigns": "sur les campagnes actives",
  "across {n} accounts · unweighted": "sur {n} comptes · non pondérée",
  "Actions": "Actions",
  "Active": "Actif",
  "Active daily budget": "Budget quotidien actif",
  "ad": "publicité",
  "Ad accounts": "Comptes publicitaires",
  "Ad manager": "Gestion des pubs",
  "Ad sets": "Ensembles de pubs",
  "Ads": "Publicités",
  "adset": "ensemble",
  "Adset Paused": "Ensemble en pause",
  "Age & gender": "Âge et sexe",
  "AI places the logo": "L'IA place le logo",
  "All": "Tous",
  "All findings": "Tous les constats",
  "All importers": "Tous les importateurs",
  "Analysis": "Analyse",
  "and live news": "et de l'actualité",
  "Animate this image": "Animer cette image",
  "Any objective": "Tous objectifs",
  "Any status": "Tous statuts",
  "App": "App",
  "App installs": "Installations d'app",
  "App Promotion": "Promotion d'app",
  "Applied": "Appliqué",
  "applied": "appliqué",
  "Apply brand persona": "Appliquer le persona de marque",
  "Apply {n} change": "Appliquer {n} modification",
  "Apply {n} changes": "Appliquer {n} modifications",
  "Applying…": "Application…",
  "Archived": "Archivé",
  "Are we paying more to reach men than women for the same result?": "Payons-nous plus cher pour toucher les hommes que les femmes pour le même résultat ?",
  "Ask about campaigns, creatives, placements, budget…": "Posez une question sur les campagnes, créatifs, placements, budget…",
  "at": "en",
  "Audience": "Audience",
  "Audit findings": "Constats d'audit",
  "Audit findings, for Excel": "Constats d'audit, pour Excel",
  "auto": "auto",
  "Average health": "Santé moyenne",
  "Awareness": "Notoriété",
  "Based on:": "Basé sur :",
  "before after": "avant / après",
  "behind the scenes": "coulisses",
  "Biggest opportunity": "Plus grosse opportunité",
  "bottom-center": "bas centre",
  "bottom-left": "bas gauche",
  "bottom-right": "bas droite",
  "Brand persona applied": "Persona de marque appliqué",
  "Breakdowns": "Répartitions",
  "Budget & pacing": "Budget et rythme",
  "By category": "Par catégorie",
  "Calendar & trends used": "Calendrier et tendances utilisés",
  "campaign": "campagne",
  "Campaign / ad set": "Campagne / ensemble",
  "Campaign Paused": "Campagne en pause",
  "Campaigns": "Campagnes",
  "Cancel": "Annuler",
  "Cargo tracking": "Suivi des marchandises",
  "Change date range": "Changer la période",
  "Change history": "Historique des modifications",
  "change staged": "modification préparée",
  "Changes are staged and previewed first — nothing is sent until you confirm. Budgets cannot be raised more than {x}× in one step or set below {min}/day. Every applied change is logged.": "Les modifications sont préparées et prévisualisées d'abord — rien n'est envoyé avant votre confirmation. Un budget ne peut pas être multiplié par plus de {x} en une fois ni descendre sous {min}/jour. Chaque modification appliquée est journalisée.",
  "changes staged": "modifications préparées",
  "Chats": "Discussions",
  "Clear filters": "Effacer les filtres",
  "click to filter": "cliquer pour filtrer",
  "Clicks": "Clics",
  "Close": "Fermer",
  "Closed": "Fermé",
  "Collapse all": "Tout replier",
  "Collapse sidebar": "Replier le menu",
  "Compare {n}": "Comparer {n}",
  "compared side by side": "comparés côte à côte",
  "Comparison": "Comparaison",
  "comparison": "comparaison",
  "Conversations": "Conversations",
  "Conversion funnel": "Entonnoir de conversion",
  "Conversions": "Conversions",
  "Copied": "Copié",
  "Copy ad text": "Copier le texte de la pub",
  "Copy language": "Langue des textes",
  "Cost per result": "Coût par résultat",
  "cost per result": "coût par résultat",
  "Cost/result": "Coût/résultat",
  "costs": "coûte",
  "Could not load budgets": "Impossible de charger les budgets",
  "Could not load this account": "Impossible de charger ce compte",
  "Could not load this account.": "Impossible de charger ce compte.",
  "Could not load this breakdown.": "Impossible de charger cette répartition.",
  "Could not reach the Marketing API.": "Impossible de joindre l'API Marketing.",
  "Country": "Pays",
  "counts compare across currencies; spend does not": "les volumes se comparent entre devises, pas les dépenses",
  "Creative": "Créatifs",
  "Creative studio": "Studio créatif",
  "Credentials come from DASHBOARD_USER / DASHBOARD_PASSWORD in .env.local": "Les identifiants viennent de DASHBOARD_USER / DASHBOARD_PASSWORD dans .env.local",
  "critical": "critique",
  "Critical": "Critique",
  "CSV data": "Données CSV",
  "Customs clearance": "Dédouanement",
  "Daily budget": "Budget quotidien",
  "Data refreshed": "Données actualisées",
  "Delete": "Supprimer",
  "Delete \"{title}\"? This cannot be undone.": "Supprimer « {title} » ? Cette action est définitive.",
  "Deleted": "Supprimé",
  "Delivery": "Diffusion",
  "Describe the clip — what happens, where, how it moves…": "Décrivez le clip — ce qui se passe, où, comment ça bouge…",
  "Describe the image — subject, setting, mood…": "Décrivez l'image — sujet, décor, ambiance…",
  "Describe the visual metaphor, then the exact text — Titre : \"… / …\"  Sous-titre : \"…\"  CTA : \"…\" (leave the text out and it writes it)": "Décrivez la métaphore visuelle, puis le texte exact — Titre : \"… / …\"  Sous-titre : \"…\"  CTA : \"…\" (sans texte, il l'écrit lui-même)",
  "Deselect": "Désélectionner",
  "Design": "Mise en page",
  "designed, with charts": "mis en page, avec graphiques",
  "Device": "Appareil",
  "directional": "indicatif",
  "Disabled": "Désactivé",
  "Discard": "Abandonner",
  "Done": "Terminé",
  "Done — {n} scenes, {s}s video. It is at the top of the gallery; the shorter steps are kept too.": "Terminé — {n} scènes, vidéo de {s} s. Elle est en haut de la galerie ; les étapes plus courtes sont conservées aussi.",
  "Download": "Télécharger",
  "dry run": "test",
  "Duration": "Durée",
  "E-commerce sellers": "E-commerçants",
  "Engagement": "Interaction",
  "Engagements": "Interactions",
  "Entities affected": "Éléments concernés",
  "Exact overlay": "Superposition exacte",
  "Expand all": "Tout déplier",
  "Expand sidebar": "Déplier le menu",
  "Export": "Exporter",
  "Extend": "Prolonger",
  "extend +{s}s up to {max}s": "prolongeable +{s} s jusqu'à {max} s",
  "Extend by 10s with Omni Flash": "Prolonger de 10 s avec Omni Flash",
  "Extend by 7s with Veo": "Prolonger de 7 s avec Veo",
  "Extend this video": "Prolonger cette vidéo",
  "extendable": "prolongeable",
  "Extending…": "Prolongation…",
  "failed": "échec",
  "Failed": "Échec",
  "feed portrait": "fil portrait",
  "feed square": "fil carré",
  "Female": "Femmes",
  "finding": "constat",
  "findings": "constats",
  "Findings": "Constats",
  "Findings by severity": "Constats par gravité",
  "First frame": "Première image",
  "First-time importers": "Primo-importateurs",
  "Fix these first": "À corriger en priorité",
  "for": "pour",
  "Format": "Format",
  "Français + Darija hook": "Français + accroche en darija",
  "Freight (sea / air / road)": "Fret (maritime / aérien / routier)",
  "Freq.": "Fréq.",
  "Frequency": "Fréquence",
  "from {n} rules": "sur {n} règles",
  "Full ad (text + layout)": "Pub complète (texte + mise en page)",
  "Generate ideas": "Générer des idées",
  "Generate image": "Générer l'image",
  "Generate video": "Générer la vidéo",
  "Generated": "Générés",
  "Generating image…": "Génération de l'image…",
  "Generations will have no brand direction until you write one.": "Les générations n'auront pas de direction de marque tant que vous n'en écrivez pas un.",
  "Google Veo 3.1 and Gemini Omni Flash, with sound. Renders take 1–3 minutes and are billed per second of video — draft with the cheaper models. Start from one of your generated ads to keep the real logo and text. The job keeps running if you navigate away — it appears in the gallery when done.": "Google Veo 3.1 et Gemini Omni Flash, avec le son. Un rendu prend 1 à 3 minutes et est facturé à la seconde — faites vos brouillons avec les modèles moins chers. Partez d'une de vos pubs générées pour garder le vrai logo et le texte. Le rendu continue si vous changez de page — il apparaît dans la galerie une fois terminé.",
  "Grace period": "Période de grâce",
  "Graph code": "code Graph",
  "Groupage / small volumes": "Groupage / petits volumes",
  "Health": "Santé",
  "Healthy": "Sain",
  "Hide history": "Masquer l'historique",
  "high": "élevé",
  "Hour of day": "Heure de la journée",
  "House style sent with every image — layout and typography are copied, concepts are not": "Style maison envoyé avec chaque image — la mise en page et la typographie sont reprises, pas les concepts",
  "I can read {c} campaigns, {a} ad sets and {d} ads on": "Je peux lire {c} campagnes, {a} ensembles et {d} publicités sur",
  "Idea generator": "Générateur d'idées",
  "Ideas": "Idées",
  "Image": "Image",
  "image": "image",
  "Image prompt & video scenes": "Prompt image et scènes vidéo",
  "Image:": "Image :",
  "Impr.": "Impr.",
  "Impressions": "Impressions",
  "in": "dans",
  "In Process": "En cours",
  "Industrial buyers": "Acheteurs industriels",
  "info": "info",
  "Insight:": "Insight :",
  "Is my budget split across ad sets hurting the learning phase?": "La répartition de mon budget entre ensembles freine-t-elle la phase d'apprentissage ?",
  "It is at the top of the gallery.": "Elle est en haut de la galerie.",
  "Landing page views": "Vues de page de destination",
  "landscape": "paysage",
  "Last 14 days": "14 derniers jours",
  "Last 28 days": "28 derniers jours",
  "Last 3 days": "3 derniers jours",
  "Last 30 days": "30 derniers jours",
  "Last 7 days": "7 derniers jours",
  "Last 90 days": "90 derniers jours",
  "Last month": "Le mois dernier",
  "Leads": "Leads",
  "Learned from:": "Appris de :",
  "Learning limited": "Apprentissage limité",
  "learning limited": "apprentissage limité",
  "Lifetime": "Depuis le début",
  "lifetime": "durée de vie",
  "lifetime spend": "dépenses totales",
  "Link clicks": "Clics sur lien",
  "live search": "recherche en direct",
  "Live web search": "Recherche web en direct",
  "Loading breakdown…": "Chargement de la répartition…",
  "Loading…": "Chargement…",
  "Logo": "Logo",
  "Logo handling": "Gestion du logo",
  "Logo sent (background removed)": "Logo envoyé (fond supprimé)",
  "Logo size": "Taille du logo",
  "Lost contact with the render — it may still be running.": "Contact perdu avec le rendu — il est peut-être toujours en cours.",
  "low": "faible",
  "Make image": "Créer l'image",
  "Make video": "Créer la vidéo",
  "Make video ({n} scenes · ~{s}s)": "Créer la vidéo ({n} scènes · ~{s} s)",
  "Male": "Hommes",
  "Match house style ({n} reference ads)": "Respecter le style maison ({n} pubs de référence)",
  "medium": "moyen",
  "Meta campaign audit & analysis": "Audit et analyse des campagnes Meta",
  "Min spend": "Dépense min.",
  "Minor issues": "Problèmes mineurs",
  "Mixed currencies ({list}).": "Devises mixtes ({list}).",
  "Model": "Modèle",
  "Most expensive cost per result": "Coût par résultat le plus élevé",
  "Name": "Nom",
  "Needs attention": "À surveiller",
  "New answers use the current window": "Les nouvelles réponses utilisent la période actuelle",
  "New chat": "Nouvelle discussion",
  "No accounts match.": "Aucun compte ne correspond.",
  "No age/gender data in this window": "Aucune donnée âge/sexe sur cette période",
  "No brand persona found at": "Aucun persona de marque trouvé dans",
  "no business portfolio": "aucun portefeuille business",
  "No campaign spend in this window": "Aucune dépense de campagne sur cette période",
  "No campaigns in this account.": "Aucune campagne dans ce compte.",
  "no change": "aucun changement",
  "No converting campaigns in this window": "Aucune campagne avec conversions sur cette période",
  "No daily spend in this window": "Aucune dépense quotidienne sur cette période",
  "No data for this breakdown": "Aucune donnée pour cette répartition",
  "No data in this window": "Aucune donnée sur cette période",
  "No delivery in this window": "Aucune diffusion sur cette période",
  "no extend": "non prolongeable",
  "No findings at this severity.": "Aucun constat à ce niveau de gravité.",
  "No findings match these filters.": "Aucun constat ne correspond à ces filtres.",
  "No findings — this account passed every rule.": "Aucun constat — ce compte respecte toutes les règles.",
  "No logo": "Sans logo",
  "No persona": "Aucun persona",
  "no persona": "sans persona",
  "No results recorded in this window": "Aucun résultat enregistré sur cette période",
  "No rows for this breakdown.": "Aucune ligne pour cette répartition.",
  "no web search": "sans recherche web",
  "None": "Aucun",
  "not reviewed": "non vérifiées",
  "Nothing generated yet.": "Rien n'a encore été généré.",
  "Nothing has been changed through this app yet.": "Rien n'a encore été modifié via cette app.",
  "Nothing matches these filters.": "Rien ne correspond à ces filtres.",
  "Now {n}s.": "Actuellement {n} s.",
  "objection handling": "réponse aux objections",
  "of": "sur",
  "offer lead magnet": "offre / aimant à leads",
  "ok": "ok",
  "On the image": "Sur l'image",
  "one scene after another": "une scène après l'autre",
  "Open": "Ouvrir",
  "Optional brief — e.g. 'order before Chinese New Year', 'tyre importers in Agadir', 'push WhatsApp leads'": "Brief optionnel — ex. « commander avant le Nouvel An chinois », « importateurs de pneus à Agadir », « pousser les leads WhatsApp »",
  "Overview": "Vue d'ensemble",
  "pain agitate solve": "problème · agitation · solution",
  "Password": "Mot de passe",
  "Pause": "Pause",
  "Paused": "En pause",
  "PDF report": "Rapport PDF",
  "Pending settlement": "Règlement en attente",
  "per currency": "par devise",
  "per result versus": "par résultat contre",
  "Performance": "Performance",
  "persona applied": "persona appliqué",
  "Pick an account to audit and analyse.": "Choisissez un compte à auditer et analyser.",
  "Placement": "Placement",
  "Platform": "Plateforme",
  "Polling failed": "Échec du suivi",
  "portrait": "portrait",
  "Position": "Position",
  "Preparing the PDF report…": "Préparation du rapport PDF…",
  "Preview full prompt": "Voir le prompt complet",
  "Prices": "Tarifs",
  "process steps": "étapes du processus",
  "Prompt only": "Prompt seul",
  "Prompt sent to the model": "Prompt envoyé au modèle",
  "proof numbers": "preuve chiffrée",
  "Purchases": "Achats",
  "Quality": "Qualité",
  "question": "question",
  "questions": "questions",
  "Reach": "Couverture",
  "Reading account overview": "Lecture de la vue d'ensemble",
  "Reading ad sets": "Lecture des ensembles",
  "Reading ads and creatives": "Lecture des pubs et créatifs",
  "Reading audit findings": "Lecture des constats d'audit",
  "Reading breakdowns": "Lecture des répartitions",
  "Reading campaigns": "Lecture des campagnes",
  "Reading your best and worst ads, the importer calendar": "Lecture de vos meilleures et pires pubs, du calendrier importateur",
  "Recoverable": "Récupérable",
  "Recoverable spend": "Dépenses récupérables",
  "Refresh": "Actualiser",
  "Refresh failed": "Échec de l'actualisation",
  "Refreshing": "Actualisation",
  "Refreshing from Meta…": "Actualisation depuis Meta…",
  "reliable": "fiable",
  "Remove scene": "Supprimer la scène",
  "Rename": "Renommer",
  "Rename chat": "Renommer la discussion",
  "Render failed": "Échec du rendu",
  "rendered at 720p": "rendu en 720p",
  "rendering": "rendu en cours",
  "Rendering…": "Rendu en cours…",
  "Request failed": "Échec de la requête",
  "Resolution": "Résolution",
  "result": "résultat",
  "Results": "Résultats",
  "results": "résultats",
  "Results by account": "Résultats par compte",
  "Resume": "Relancer",
  "Retail & wholesale": "Détail et gros",
  "Review changes": "Vérifier les modifications",
  "Review in audit →": "Voir dans l'audit →",
  "Review — nothing has been sent yet": "Vérification — rien n'a encore été envoyé",
  "reviewed": "vérifiées",
  "Risk review": "Vérification des risques",
  "Running": "Exécution de",
  "Sales": "Ventes",
  "Saved chat from {date} on": "Discussion du {date} sur",
  "Scene": "Scène",
  "scene": "scène",
  "Scene {i}/{n}": "Scène {i}/{n}",
  "scenes": "scènes",
  "Search accounts…": "Rechercher un compte…",
  "Search by name…": "Rechercher par nom…",
  "Search findings, campaigns, ad sets…": "Rechercher un constat, une campagne, un ensemble…",
  "seasonal urgency": "urgence saisonnière",
  "Select": "Sélectionner",
  "Select a start date": "Choisir une date de début",
  "Select account": "Choisir un compte",
  "select end date": "choisir la date de fin",
  "Send": "Envoyer",
  "Service": "Service",
  "Severity": "Gravité",
  "Share": "Part",
  "Show saved chats": "Afficher les discussions",
  "Showing": "Affichage de",
  "Sign in": "Se connecter",
  "Sign out": "Se déconnecter",
  "Significant problems": "Problèmes importants",
  "Signing in…": "Connexion…",
  "skipped": "ignoré",
  "SME importers (China / Turkey)": "PME importatrices (Chine / Turquie)",
  "Sort findings": "Trier les constats",
  "Sourcing & supplier checks": "Sourcing et contrôle fournisseurs",
  "Spend": "Dépenses",
  "Spend and cost figures are shown per currency and never added together — a combined total would be meaningless. Counts and rates (results, clicks, CTR) do combine.": "Les dépenses et les coûts sont affichés par devise et jamais additionnés — un total combiné n'aurait pas de sens. Les volumes et les taux (résultats, clics, CTR) s'additionnent.",
  "Spend by account": "Dépenses par compte",
  "Spend by campaign": "Dépenses par campagne",
  "Spend per day": "Dépenses par jour",
  "Spend this window": "Dépenses de la période",
  "square": "carré",
  "Staged changes": "Modifications préparées",
  "Start from": "Partir de",
  "starting": "démarrage",
  "Starting render…": "Lancement du rendu…",
  "Status": "Statut",
  "Step {i}/{n}": "Étape {i}/{n}",
  "Steps": "Étapes",
  "Stop": "Arrêter",
  "Stop after this scene": "Arrêter après cette scène",
  "Stop after this step": "Arrêter après cette étape",
  "Stopped. The render already started still finishes on Google's side.": "Arrêté. Le rendu déjà lancé se termine quand même chez Google.",
  "story reel vertical": "story / reel vertical",
  "Strategist": "Stratège",
  "Structure": "Structure",
  "Studying your ads…": "Analyse de vos pubs…",
  "Switch ad account": "Changer de compte publicitaire",
  "testimonial ugc": "témoignage UGC",
  "Tests:": "Teste :",
  "The prompt above is scene 1 ({s}s). Each scene below continues the previous one from its last frame (+{step}s).": "Le prompt ci-dessus est la scène 1 ({s} s). Chaque scène ci-dessous prolonge la précédente depuis sa dernière image (+{step} s).",
  "then brainstorming and discarding the generic. Usually 1–2 minutes.": "puis brainstorming et élimination du générique. Environ 1 à 2 minutes.",
  "Thinking": "Réflexion",
  "This answer failed:": "Cette réponse a échoué :",
  "This audit is incomplete.": "Cet audit est incomplet.",
  "This chat could not be opened": "Impossible d'ouvrir cette discussion",
  "This month": "Ce mois-ci",
  "This page writes to your live ad account.": "Cette page modifie votre compte publicitaire en direct.",
  "This quarter": "Ce trimestre",
  "This week": "Cette semaine",
  "This window": "Cette période",
  "Today": "Aujourd'hui",
  "Toggle ad sets": "Afficher les ensembles",
  "Token expires in": "Le jeton expire dans",
  "too long for": "trop long pour",
  "top {n}": "top {n}",
  "top-left": "haut gauche",
  "top-right": "haut droite",
  "Total": "Total",
  "Tracking": "Suivi / pixel",
  "Traffic": "Trafic",
  "Unsettled": "Impayé",
  "Unstage": "Retirer",
  "untitled": "sans titre",
  "up to": "jusqu'à",
  "up to {max}s in total. Each step is saved as a new video; the original is kept.": "jusqu'à {max} s au total. Chaque étape est enregistrée comme une nouvelle vidéo ; l'originale est conservée.",
  "Update": "Appliquer",
  "upscaled": "agrandi",
  "Username": "Identifiant",
  "Validate with Meta (no change)": "Valider avec Meta (sans modifier)",
  "validated": "validé",
  "Validation result": "Résultat de la validation",
  "Veo only extends 720p videos (this one is {r})": "Veo ne prolonge que les vidéos 720p (celle-ci est en {r})",
  "via": "via",
  "Video": "Vidéo",
  "video": "vidéo",
  "Video continuity:": "Continuité vidéo :",
  "Video needs": "La vidéo nécessite",
  "Video scenes": "Scènes vidéo",
  "Video:": "Vidéo :",
  "View all →": "Tout voir →",
  "View everything this app has changed": "Voir tout ce que l'app a modifié",
  "Visual only (no text)": "Visuel seul (sans texte)",
  "vs previous period of equal length": "vs période précédente de même durée",
  "vs {v} last period": "vs {v} la période précédente",
  "Warehousing & delivery": "Entreposage et livraison",
  "weak": "faible",
  "web search used": "recherche web utilisée",
  "What happens next — e.g. 'the camera follows the container onto a truck leaving Tanger Med, ends on a calm wide shot of the port at sunset'": "Ce qui se passe ensuite — ex. « la caméra suit le conteneur jusqu'au camion qui quitte Tanger Med, finit sur un plan large et calme du port au coucher du soleil »",
  "What happens next, from the last frame of the previous scene…": "Ce qui se passe ensuite, depuis la dernière image de la scène précédente…",
  "What should I fix first, and what will it save?": "Que dois-je corriger en premier, et combien cela fera-t-il économiser ?",
  "Which creatives are working and which should I kill?": "Quels créatifs fonctionnent et lesquels arrêter ?",
  "Which placements are wasting money?": "Quels placements gaspillent de l'argent ?",
  "whole account": "tout le compte",
  "Whole offer (one partner)": "Offre complète (un seul partenaire)",
  "With Issues": "Avec problèmes",
  "Working": "En cours",
  "Working…": "En cours…",
  "worst performer highlighted · others in grey": "le moins performant en couleur · les autres en gris",
  "Write me a plan for next week.": "Rédige-moi un plan pour la semaine prochaine.",
  "Yesterday": "Hier",
  "Your chats on this account will be saved here.": "Vos discussions sur ce compte seront enregistrées ici.",
  "Your marketing engineer": "Votre ingénieur marketing",
  "your real ads + persona + importer calendar": "vos vraies pubs + persona + calendrier importateur",
  "{a} ok · {f} failed · {s} skipped": "{a} ok · {f} en échec · {s} ignorées",
  "{a}–{b}s per render": "{a}–{b} s par rendu",
  "{label} per day": "{label} par jour",
  "{metric} by age and gender": "{metric} par âge et sexe",
  "{metric} by {cut}": "{metric} par {cut}",
  "{model} allows up to {n} scenes.": "{model} permet jusqu'à {n} scènes.",
  "{model} continues it from the last frame, as one continuous shot — +{s}s per step.": "{model} la prolonge depuis la dernière image, en un seul plan continu — +{s} s par étape.",
  "{model} videos stop at {max}s — use at most {n} scenes.": "Les vidéos {model} s'arrêtent à {max} s — utilisez au plus {n} scènes.",
  "{name} and {n} others": "{name} et {n} autres",
  "{n} account(s) could not be loaded.": "{n} compte(s) n'ont pas pu être chargés.",
  "{n} accounts": "{n} comptes",
  "{n} accounts compared": "{n} comptes comparés",
  "{n} ad sets": "{n} ensembles",
  "{n} affected": "{n} concernés",
  "{n} already in that state": "{n} déjà dans cet état",
  "{n} clicks": "{n} clics",
  "{n} days": "{n} jours",
  "{n} entities": "{n} éléments",
  "{n} impressions": "{n} impressions",
  "{n} logos": "{n} logos",
  "{n} need attention": "{n} à traiter",
  "{n} reached": "{n} touchés",
  "{n} rows": "{n} lignes",
  "{n} scopes": "{n} autorisations",
  "{n} selected": "{n} sélectionné(s)",
  "{n} to apply": "{n} à appliquer",
  "{n} winning creatives viewed": "{n} créatifs gagnants analysés",
  "{n}s video": "vidéo de {n} s",
  "{pct} of previous": "{pct} de l'étape précédente",
  "{pct} of spend this window": "{pct} des dépenses de la période",
  "{pct} of {what}": "{pct} des {what}",
  "{sources} could not be fetched, so some findings are missing and the health score reads higher than it should. Try Refresh — this is usually Meta rate-limiting.": "{sources} n'ont pas pu être récupérés : certains constats manquent et le score de santé est surévalué. Réessayez Actualiser — c'est généralement une limite de requêtes Meta.",
  "{x}x the cost for the same outcome.": "soit {x}x le coût pour le même résultat.",
  "~5-10s, timed by the prompt": "~5-10 s, rythmé par le prompt",
  "~5–10s": "~5–10 s",
};

export default FR;
